apiVersion: kubeaddons.mesosphere.io/v1beta2
kind: Addon
metadata:
  annotations:
    appversion.kubeaddons.mesosphere.io/elasticsearchexporter: 1.1.0
    catalog.kubeaddons.mesosphere.io/addon-revision: 1.1.0-4
    values.chart.helm.kubeaddons.mesosphere.io/elasticsearchexportercustom: https://raw.githubusercontent.com/mesosphere/charts/73fba37/stable/elasticsearch-exporter/values.yaml
  labels:
    kubeaddons.mesosphere.io/name: elasticsearchexporterexternal
  name: elasticsearchexporterexternal
  namespace: customaddons
spec:
  chartReference:
    chart: prometheus-elasticsearch-exporter
    repo: https://prometheus-community.github.io/helm-charts
    values: |
      ---
      # As defined in the readme file when migrating from old chart to new chart
      # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
      # we should override the full name and name in order to do upgrades for services and deployments
      fullnameOverride: elasticsearchexporter-customaddons-elasticsearch-exporter
      nameOverride: elasticsearch-external-exporter
      es:
        uri: http://elasticsearch-customaddons-client:9200
      service:
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
        metricsPort:
          name: metrics
    version: 4.0.0
  cloudProvider:
  - enabled: true
    name: aws
  - enabled: true
    name: azure
  - enabled: true
    name: gcp
  - enabled: true
    name: vsphere
  - enabled: false
    name: docker
  - enabled: true
    name: none
  kubernetes:
    minSupportedVersion: v1.15.6
  requires:
  - matchLabels:
      kubeaddons.mesosphere.io/name: elastic-external
