apiVersion: kubeaddons.mesosphere.io/v1beta2
kind: ClusterAddon
metadata:
  annotations:
    appversion.kubeaddons.mesosphere.io/metallb: 0.9.3
    catalog.kubeaddons.mesosphere.io/addon-revision: 0.9.3-5
    values.chart.helm.kubeaddons.mesosphere.io/metallb: https://raw.githubusercontent.com/mesosphere/charts/1ce2aaa/stable/metallb/values.yaml
  labels:
    kubeaddons.mesosphere.io/name: metallb
    kubeaddons.mesosphere.io/provides: loadbalancer
  name: metallb-custom
spec:
  chartReference:
    chart: metallb
    repo: http://custom-helm-charts.kubeaddons.svc
    values: |
      ---
      controller:
        image:
          repository: metallb/controller
          tag: v0.9.3
        requests:
          cpu: 100m
          memory: 100Mi
      prometheus:
        metrics:
          enabled: true
          labels:
            servicemonitor.kubeaddons.mesosphere.io/path: metrics
      speaker:
        image:
          repository: metallb/speaker
          tag: v0.9.3
        requests:
          cpu: 100m
          memory: 100Mi
    version: 0.12.100
  cloudProvider:
  - enabled: false
    name: azure
  - enabled: true
    name: vsphere
    values: |
      configInline:
        address-pools:
        - name: default
          protocol: layer2
          # configure addresses if addon is enabled
          addresses: []
  - enabled: true
    name: docker
    values: |
      configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 172.17.1.200-172.17.1.250
  - enabled: true
    name: none
    values: |
      configInline:
        address-pools:
        - name: default
          protocol: layer2
          # configure addresses for your network
          addresses: []
  kubernetes:
    minSupportedVersion: v1.15.6

