---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: argocd
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: argocd
    # TODO: we're temporarily supporting dependency on an existing default storage class
    # on the cluster, this hack will trigger re-queue on Addons until one exists
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.1-1"
    appversion.kubeaddons.mesosphere.io/argocd: "1.0.1"
spec:
  kubernetes:
    minSupportedVersion: v1.19.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  kudoReference:
    appVersion: 2.0.1
    package: argocd
    repo: https://raw.githubusercontent.com/arbhoj/kudo-repo/master
    version: 1.0.0
    parameters: |
      host: argouat.sgicorp.spencergifts.com
      konvoy_host: konuat.sgicorp.spencergifts.com    
