---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: common
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: common
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.1-1"
    appversion.kubeaddons.mesosphere.io/common: "1.0.1"
spec:
  kubernetes:
    minSupportedVersion: v1.19.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
    - name: vsphere
      enabled: true       
  chartReference:
    chart: common
    repo: https://raw.githubusercontent.com/arbhoj/helm-images/master/custom-helm-charts/
    version: 0.1.0
    values: |
      dummy: value
  requires:
  - matchLabels:
      kubeaddons.mesosphere.io/name: dex
  - matchLabels:
      kubeaddons.mesosphere.io/name: f5
